name = "SubglobalSensitivityAnalysis"
uuid = "e5cc3859-2e89-4a16-aeca-5b21eb6ba5f1"
authors = ["Thomas Wutzler <twutz@bgc-jena.mpg.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
